/**
 * Configures the shared Next.js application generated by create-next-app.
 * Both hosts use normal Next.js server rendering; desktop starts that server
 * locally rather than exporting a separate static version of the UI.
 */
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Next.js locks development output to one server. Each host gets its own
  // output directory while production uses a single shared build.
  distDir: process.env.CHULANE_DESKTOP_DEV === "1" ? ".next-desktop" : ".next",
};

export default nextConfig;
