/**
 * Provides the browser-side Markdown repository for the documentation app.
 * Development uses the guarded Vite endpoint; static builds use bundled pages
 * and expose edited Markdown as a download instead of pretending files are writable.
 */

import { bundledDocuments } from "virtual:rivto-documents";

const DOCUMENTS_ENDPOINT = "/__rivto-documents";

export interface DocumentationPage {
  path: string;
  content: string;
  modifiedAt: number;
}

export interface DocumentationImage {
  markdownSource: string;
}

/**
 * Creates a new ordered Markdown file through the local development server.
 *
 * @param path Numeric-prefixed relative path generated by the navigation layer.
 * @param title Human-readable H1 used as initial document content.
 * @returns Newly persisted page and its modification token.
 */
export async function createDocumentationPage(
  path: string,
  title: string,
): Promise<DocumentationPage> {
  const response = await fetch(DOCUMENTS_ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ path, content: `# ${title}\n\n` }),
  });
  const result = await response.json() as DocumentationPage | { message?: string };
  if (!response.ok) {
    const message = "message" in result ? result.message : undefined;
    throw new Error(message ?? "Unable to create Markdown document.");
  }
  return result as DocumentationPage;
}

/**
 * Deletes one page through the local development server.
 *
 * @param page Canonical page and modification token to delete.
 * @returns Promise completed after the Markdown file is removed.
 */
export async function deleteDocumentationPage(page: DocumentationPage): Promise<void> {
  const response = await fetch(`${DOCUMENTS_ENDPOINT}/${encodeURIComponent(page.path)}`, {
    method: "DELETE",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ expectedModifiedAt: page.modifiedAt }),
  });
  if (!response.ok) {
    const result = await response.json() as { message?: string };
    throw new Error(result.message ?? "Unable to delete Markdown document.");
  }
}

/**
 * Stores a pasted image inside the selected page's asset folder.
 *
 * @param page Owning Markdown page.
 * @param image Browser image file from the clipboard.
 * @returns Portable source path to insert into the Markdown document.
 */
export async function uploadDocumentationImage(
  page: DocumentationPage,
  image: File,
): Promise<DocumentationImage> {
  const response = await fetch("/__rivto-images", {
    method: "POST",
    headers: {
      "Content-Type": image.type,
      "X-Rivto-Page-Path": encodeURIComponent(page.path),
    },
    body: image,
  });
  const result = await response.json() as DocumentationImage | { message?: string };
  if (!response.ok) {
    const message = "message" in result ? result.message : undefined;
    throw new Error(message ?? "Unable to save pasted image.");
  }
  return result as DocumentationImage;
}

/**
 * Loads current documents from disk in development or from the static bundle.
 *
 * @returns Canonical documentation pages in navigation order.
 */
export async function loadDocumentationPages(): Promise<DocumentationPage[]> {
  let pages = bundledDocuments;
  if (import.meta.env.DEV) {
    const response = await fetch(DOCUMENTS_ENDPOINT);
    if (!response.ok) {
      throw new Error("Unable to load Markdown documents.");
    }
    pages = await response.json() as DocumentationPage[];
  }
  return pages;
}

/**
 * Writes a page through the local development server.
 *
 * @param page Page and modification token loaded by the browser.
 * @param content Current Markdown serialized by Tiptap.
 * @returns Saved page with its refreshed modification token.
 */
export async function saveDocumentationPage(
  page: DocumentationPage,
  content: string,
): Promise<DocumentationPage> {
  const response = await fetch(`${DOCUMENTS_ENDPOINT}/${encodeURIComponent(page.path)}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ content, expectedModifiedAt: page.modifiedAt }),
  });
  const result = await response.json() as DocumentationPage | { message?: string };
  if (!response.ok) {
    const message = "message" in result ? result.message : undefined;
    throw new Error(message ?? "Unable to save Markdown document.");
  }
  return result as DocumentationPage;
}

/**
 * Downloads Markdown when the static site has no local filesystem endpoint.
 *
 * @param pagePath Relative source filename used for the download.
 * @param content Current Markdown serialized by Tiptap.
 * @returns Nothing.
 */
export function downloadDocumentationPage(pagePath: string, content: string): void {
  const link = document.createElement("a");
  const objectUrl = URL.createObjectURL(new Blob([content], { type: "text/markdown;charset=utf-8" }));
  link.href = objectUrl;
  link.download = pagePath.split("/").at(-1) ?? "document.md";
  link.click();
  URL.revokeObjectURL(objectUrl);
}

/**
 * Derives a readable title from the first Markdown H1 or the file name.
 *
 * @param page Documentation page to label.
 * @returns Human-readable navigation title.
 */
export function getDocumentationPageTitle(page: DocumentationPage): string {
  const heading = page.content.match(/^#\s+(.+)$/m)?.[1]?.trim();
  const fileName = page.path.split("/").at(-1)?.replace(/\.md$/i, "") ?? page.path;
  return heading || fileName.replace(/^\d+-/, "").replaceAll(/[-_]/g, " ");
}
