/** Stable action IDs used by creation-time keyboard overrides. */
export const KEYBOARD_BINDING_IDS = {
  historyUndo: "history.undo",
  historyRedo: "history.redo",
  clipboardPasteAsPlainText: "clipboard.paste-as-plain-text",
  clipboardPasteAsPlainTextRelease: "clipboard.paste-as-plain-text-release",
  blockCreate: "block.create",
  blockSeparatorCreate: "block.separator-create",
  selectionDelete: "selection.delete",
  blockOutdentAtStart: "block.outdent-at-start",
  blockMergeBackward: "block.merge-backward",
  blockMergeForward: "block.merge-forward",
  emptyBlockReset: "block.reset-empty",
  blockIndent: "block.indent",
  blockOutdent: "block.outdent",
  caretLeft: "caret.left",
  caretRight: "caret.right",
  caretUp: "caret.up",
  caretDown: "caret.down",
  caretExtendUp: "caret.extend-up",
  caretExtendDown: "caret.extend-down",
  blockSelectionUp: "selection.block-up",
  blockSelectionDown: "selection.block-down",
  blockSelectionExtendUp: "selection.block-extend-up",
  blockSelectionExtendDown: "selection.block-extend-down",
  blockSelectionGrowUp: "selection.block-grow-up",
  blockSelectionGrowDown: "selection.block-grow-down",
  blockSelectionCaretLeft: "selection.block-caret-left",
  blockSelectionCaretRight: "selection.block-caret-right",
  blockMoveUp: "block.move-up",
  blockMoveDown: "block.move-down",
  blockCollapse: "block.collapse",
  blockExpand: "block.expand",
  blockToggleCollapse: "block.toggle-collapse",
  slashPrevious: "slash.previous",
  slashNext: "slash.next",
  slashExecute: "slash.execute",
  slashClose: "slash.close",
  blockSelectionModifierDown: "selection.block-modifier-down",
  blockSelectionModifierUp: "selection.block-modifier-up",
  edgelessSelectionClear: "edgeless.selection-clear",
  edgelessSelectionDelete: "edgeless.selection-delete",
  edgelessMoveLeft: "edgeless.move-left",
  edgelessMoveRight: "edgeless.move-right",
  edgelessMoveUp: "edgeless.move-up",
  edgelessMoveDown: "edgeless.move-down",
  edgelessMoveFastLeft: "edgeless.move-fast-left",
  edgelessMoveFastRight: "edgeless.move-fast-right",
  edgelessMoveFastUp: "edgeless.move-fast-up",
  edgelessMoveFastDown: "edgeless.move-fast-down",
  edgelessTransformCancel: "edgeless.transform-cancel",
  edgelessToolSelect: "edgeless.tool-select",
  edgelessPanStart: "edgeless.pan-start",
  edgelessPanStop: "edgeless.pan-stop",
} as const;

/** Default shortcuts keyed by their public binding IDs. */
export const BUILTIN_KEYMAP: Readonly<Record<string, readonly string[]>> = {
  [KEYBOARD_BINDING_IDS.historyUndo]: ["Primary+z"],
  [KEYBOARD_BINDING_IDS.historyRedo]: ["Primary+Shift+z", "Primary+y"],
  [KEYBOARD_BINDING_IDS.clipboardPasteAsPlainText]: ["Primary+Shift+v"],
  [KEYBOARD_BINDING_IDS.clipboardPasteAsPlainTextRelease]: [
    "Primary+Shift+v",
    "Primary+v",
    "Shift+v",
    "v",
  ],
  [KEYBOARD_BINDING_IDS.blockCreate]: ["Enter"],
  [KEYBOARD_BINDING_IDS.blockSeparatorCreate]: ["Primary+Shift+Enter"],
  [KEYBOARD_BINDING_IDS.selectionDelete]: ["Backspace", "Delete"],
  [KEYBOARD_BINDING_IDS.blockOutdentAtStart]: ["Backspace"],
  [KEYBOARD_BINDING_IDS.blockMergeBackward]: ["Backspace"],
  [KEYBOARD_BINDING_IDS.blockMergeForward]: ["Delete"],
  [KEYBOARD_BINDING_IDS.emptyBlockReset]: ["Backspace"],
  [KEYBOARD_BINDING_IDS.blockIndent]: ["Tab"],
  [KEYBOARD_BINDING_IDS.blockOutdent]: ["Shift+Tab"],
  [KEYBOARD_BINDING_IDS.caretLeft]: ["ArrowLeft"],
  [KEYBOARD_BINDING_IDS.caretRight]: ["ArrowRight"],
  [KEYBOARD_BINDING_IDS.caretUp]: ["ArrowUp"],
  [KEYBOARD_BINDING_IDS.caretDown]: ["ArrowDown"],
  [KEYBOARD_BINDING_IDS.caretExtendUp]: ["Shift+ArrowUp"],
  [KEYBOARD_BINDING_IDS.caretExtendDown]: ["Shift+ArrowDown"],
  [KEYBOARD_BINDING_IDS.blockSelectionUp]: ["ArrowUp"],
  [KEYBOARD_BINDING_IDS.blockSelectionDown]: ["ArrowDown"],
  [KEYBOARD_BINDING_IDS.blockSelectionExtendUp]: ["Shift+ArrowUp"],
  [KEYBOARD_BINDING_IDS.blockSelectionExtendDown]: ["Shift+ArrowDown"],
  [KEYBOARD_BINDING_IDS.blockSelectionGrowUp]: ["Alt+ArrowUp"],
  [KEYBOARD_BINDING_IDS.blockSelectionGrowDown]: ["Alt+ArrowDown"],
  [KEYBOARD_BINDING_IDS.blockSelectionCaretLeft]: ["ArrowLeft"],
  [KEYBOARD_BINDING_IDS.blockSelectionCaretRight]: ["ArrowRight"],
  [KEYBOARD_BINDING_IDS.blockMoveUp]: ["Alt+Shift+ArrowUp"],
  [KEYBOARD_BINDING_IDS.blockMoveDown]: ["Alt+Shift+ArrowDown"],
  [KEYBOARD_BINDING_IDS.blockCollapse]: ["Primary+ArrowUp"],
  [KEYBOARD_BINDING_IDS.blockExpand]: ["Primary+ArrowDown"],
  [KEYBOARD_BINDING_IDS.blockToggleCollapse]: ["Primary+;"],
  [KEYBOARD_BINDING_IDS.slashPrevious]: ["ArrowUp"],
  [KEYBOARD_BINDING_IDS.slashNext]: ["ArrowDown"],
  [KEYBOARD_BINDING_IDS.slashExecute]: ["Enter"],
  [KEYBOARD_BINDING_IDS.slashClose]: ["Escape"],
  [KEYBOARD_BINDING_IDS.blockSelectionModifierDown]: ["Control", "Meta"],
  [KEYBOARD_BINDING_IDS.blockSelectionModifierUp]: ["Control", "Meta"],
  [KEYBOARD_BINDING_IDS.edgelessSelectionClear]: ["Escape"],
  [KEYBOARD_BINDING_IDS.edgelessSelectionDelete]: ["Backspace", "Delete"],
  [KEYBOARD_BINDING_IDS.edgelessMoveLeft]: ["ArrowLeft"],
  [KEYBOARD_BINDING_IDS.edgelessMoveRight]: ["ArrowRight"],
  [KEYBOARD_BINDING_IDS.edgelessMoveUp]: ["ArrowUp"],
  [KEYBOARD_BINDING_IDS.edgelessMoveDown]: ["ArrowDown"],
  [KEYBOARD_BINDING_IDS.edgelessMoveFastLeft]: ["Shift+ArrowLeft"],
  [KEYBOARD_BINDING_IDS.edgelessMoveFastRight]: ["Shift+ArrowRight"],
  [KEYBOARD_BINDING_IDS.edgelessMoveFastUp]: ["Shift+ArrowUp"],
  [KEYBOARD_BINDING_IDS.edgelessMoveFastDown]: ["Shift+ArrowDown"],
  [KEYBOARD_BINDING_IDS.edgelessTransformCancel]: ["Escape"],
  [KEYBOARD_BINDING_IDS.edgelessToolSelect]: ["Escape"],
  [KEYBOARD_BINDING_IDS.edgelessPanStart]: ["Space"],
  [KEYBOARD_BINDING_IDS.edgelessPanStop]: ["Space"],
};
